### ISSUE TITLE
DROP INDEX segfault

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#175]
From statement "drop index expr_comp_key_index;" in  sql/yb_insert_conflict.sql of yb_pg_dml_serial_schedule

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055eb75c70754 in k2pg::sql::catalog::SqlCatalogClient::DeleteIndexTable (this=<optimized out>,
--Type <RET> for more, q to quit, c to continue without paging--
    database_oid=<optimized out>, table_oid=<optimized out>, base_table_oid=base_table_oid@entry=0x0,
    wait=wait@entry=true) at /build/src/k2/connector/pggate/catalog/sql_catalog_client.cc:160
160       *base_table_oid = response.baseIndexTableOid;
[Current thread is 1 (Thread 0x7faf8725bdc0 (LWP 4047))]
(gdb) bt
#0  0x000055eb75c70754 in k2pg::sql::catalog::SqlCatalogClient::DeleteIndexTable (this=<optimized out>,
    database_oid=<optimized out>, table_oid=<optimized out>, base_table_oid=base_table_oid@entry=0x0,
    wait=wait@entry=true) at /build/src/k2/connector/pggate/catalog/sql_catalog_client.cc:160
#1  0x000055eb75c63cb7 in k2pg::gate::PgSession::DropIndex (this=<optimized out>, index_object_id=...,
    base_table_oid=base_table_oid@entry=0x0, wait=wait@entry=true)
    at /build/src/k2/connector/entities/entity_ids.h:159
#2  0x000055eb75ccaaf7 in k2pg::gate::PgDropIndex::Exec (this=this@entry=0x7faf70035040)
    at /usr/include/c++/9/bits/shared_ptr_base.h:1020

**Comment by jfunston** [comment]
wrong repo
