### ISSUE TITLE
TPCC load crash issue

### ISSUE THREAD

**Issue by johnfangAFW** [futurewei-cloud/chogori-platform#241]
tpcc_client: /build/src/core/future.cc:150: void seastar::future_state_base::ignore(): Assertion `0 && "invalid state for ignore"' failed.
Aborting on shard 4.
Backtrace:
0x00000000003387ec
0x00000000002fff60
0x0000000000300262
0x0000000000300322
0x00002a34acdfb3bf
/lib/x86_64-linux-gnu/libc.so.6+0x000000000004618a
/lib/x86_64-linux-gnu/libc.so.6+0x0000000000025858
/lib/x86_64-linux-gnu/libc.so.6+0x0000000000025728
/lib/x86_64-linux-gnu/libc.so.6+0x0000000000036f35
0x00000000002ca4fb
0x000000000014540f
0x00000000001455d7
0x00000000002faa97
0x00000000002fade8
0x0000000000324ddd
0x000000000032b7bb
0x00000000002e07c1
/lib/x86_64-linux-gnu/libpthread.so.0+0x0000000000009608
/lib/x86_64-linux-gnu/libc.so.6+0x0000000000122292

**Comment by johnfangAFW** [comment]
# echo "0x00000000003387ec
> 0x00000000002fff60
> 0x0000000000300262
> 0x0000000000300322
> 0x00002a34acdfb3bf
> /lib/x86_64-linux-gnu/libc.so.6+0x000000000004618a
> /lib/x86_64-linux-gnu/libc.so.6+0x0000000000025858
> /lib/x86_64-linux-gnu/libc.so.6+0x0000000000025728
> /lib/x86_64-linux-gnu/libc.so.6+0x0000000000036f35
> 0x00000000002ca4fb
> 0x000000000014540f
> 0x00000000001455d7
> 0x00000000002faa97
> 0x00000000002fade8
> 0x0000000000324ddd
> 0x000000000032b7bb
> 0x00000000002e07c1
> /lib/x86_64-linux-gnu/libpthread.so.0+0x0000000000009608
> /lib/x86_64-linux-gnu/libc.so.6+0x0000000000122292" | addr2line -e ./build/src/k2/cmd/tpcc/tpcc_client
/build/include/seastar/util/backtrace.hh:59
/build/src/core/reactor.cc:732
/build/src/core/reactor.cc:760
/build/src/core/reactor.cc:3550
??:0
??:0
??:0
??:0
??:0
/build/src/core/future.cc:150
/usr/local/include/seastar/core/future.hh:1872
/usr/local/include/seastar/core/future.hh:1668
/build/src/core/reactor.cc:2212
/build/src/core/reactor.cc:2621
/build/src/core/reactor.cc:2605
/build/src/core/reactor.cc:3981
/usr/include/c++/9/bits/std_function.h:688
??:0
??:0

**Comment by johnfangAFW** [comment]
cool. thanks. The root cause was that we ignored the future that was in an invalid state, which was not allowed by seastar. Let us see if we could resolve this issue by removing it.

**Comment by johnfangAFW** [comment]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f0500d3a92e in __GI_abort () at abort.c:100
#2  0x00007f0500d3a729 in __assert_fail_base (fmt=0x7f0500ed0588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x5583da4e8da0 "(success)", file=0x5583da4e5cd8 "/build/src/k2/cmd/tpcc/verify.cpp", line=80, function=<optimized out>)
    at assert.c:92
#3  0x00007f0500d4bf36 in __GI___assert_fail (assertion=assertion@entry=0x5583da4e8da0 "(success)", file=file@entry=0x5583da4e5cd8 "/build/src/k2/cmd/tpcc/verify.cpp", line=line@entry=80, 
    function=function@entry=0x5583da4e6890 "AtomicVerify::runPaymentTxn(PaymentT&)::<lambda(bool)>") at assert.c:101
#4  0x00005583da19868e in AtomicVerify::<lambda(bool)>::operator()(bool) (success=false, __closure=<optimized out>) at /build/src/k2/cmd/tpcc/verify.cpp:80
#5  0x00005583da198fd8 in AtomicVerify::<lambda(bool)>::operator() (success=<optimized out>, __closure=<optimized out>) at /usr/local/include/seastar/core/future.hh:567
#6  std::__invoke_impl<void, AtomicVerify::runPaymentTxn(PaymentT&)::<lambda(bool)>&, bool> (__f=...) at /usr/include/c++/9/bits/invoke.h:60
#7  std::__invoke<AtomicVerify::runPaymentTxn(PaymentT&)::<lambda(bool)>&, bool> (__fn=...) at /usr/include/c++/9/bits/invoke.h:95
#8  std::invoke<AtomicVerify::runPaymentTxn(PaymentT&)::<lambda(bool)>&, bool> (__fn=...) at /usr/include/c++/9/functional:81
#9  seastar::internal::future_invoke<AtomicVerify::runPaymentTxn(PaymentT&)::<lambda(bool)>&, bool> (func=..., v=@0x6000001c8b18: false) at /usr/local/include/seastar/core/future.hh:1211
#10 seastar::future<bool>::<lambda(pr_type&&, AtomicVerify::runPaymentTxn(PaymentT&)::<lambda(bool)>&, seastar::future<bool>::future_state&&)>::<lambda()>::operator() (this=<optimized out>) at /usr/local/include/seastar/core/future.hh:1582
#11 seastar::futurize<void>::satisfy_with_result_of<seastar::future<T>::then_impl_nrvo(Func&&) [with Func = AtomicVerify::runPaymentTxn(PaymentT&)::<lambda(bool)>; Result = seastar::future<>; T = bool]::<lambda(pr_type&&, AtomicVerify::runPaymentTxn(PaymentT&)::<lambda(bool)>&, seastar::future<bool>::future_state&&)>::<lambda()> > (func=..., pr=...) at /usr/local/include/seastar/core/future.hh:2117
#12 seastar::future<bool>::<lambda(pr_type&&, AtomicVerify::runPaymentTxn(PaymentT&)::<lambda(bool)>&, seastar::future<bool>::future_state&&)>::operator() (this=<optimized out>, func=..., state=..., pr=...)
    at /usr/local/include/seastar/core/future.hh:1575
#13 seastar::continuation<seastar::internal::promise_base_with_type<void>, AtomicVerify::runPaymentTxn(PaymentT&)::<lambda(bool)>, seastar::future<T>::then_impl_nrvo(Func&&) [with Func = AtomicVerify::runPaymentTxn(PaymentT&)::<lambda(bool)>; Result = seastar::future<>; T = bool]::<lambda(pr_type&&, AtomicVerify::runPaymentTxn(PaymentT&)::<lambda(bool)>&, seastar::future<bool>::future_state&&)>, bool>::run_and_dispose(void) (this=0x6000001c8b00) at /usr/local/include/seastar/core/future.hh:767
#14 0x00005583da2e2ba8 in seastar::reactor::run_tasks (this=0x6000001c6000, tq=...) at /build/src/core/reactor.cc:2212
#15 0x00005583da2e2ef9 in seastar::reactor::run_some_tasks (this=this@entry=0x6000001c6000) at /build/src/core/reactor.cc:2621
#16 0x00005583da30ceee in seastar::reactor::run_some_tasks (this=0x6000001c6000) at /build/src/core/reactor.cc:2785
#17 seastar::reactor::run (this=0x6000001c6000) at /build/src/core/reactor.cc:2785
#18 0x00005583da2ae28f in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7ffec7c133c0, ac=<optimized out>, av=<optimized out>, func=...) at /build/include/seastar/core/reactor.hh:739
#19 0x00005583da1e6a75 in k2::App::start (this=0x7ffec7c133b0, argc=<optimized out>, argv=<optimized out>) at /usr/include/c++/9/bits/std_function.h:87
#20 0x00005583da091891 in main (argc=31, argv=0x7ffec7c137d8) at /build/src/k2/cmd/tpcc/tpcc_client.cpp:441
